### ISSUE TITLE
Can_MainFunction_Read_Fix

### ISSUE THREAD

**Issue by Muhammed-ELGendy** [autosarzs/Dev#41]
1- CAN_CONTROLLERS_NUMBER is defined as 1U , which is wrong definition. It is supposed to be (uint8)2
2- Det_ReportError function is left as a comment In the first if statement inside the loop, it should not be left as a comment
3- receive is defined repeatedly in Can.h and Can_GeneralTypes.h in different case letters, it should be defined in Can.h only.
4- controllerId is sent as the first parameter to CANMessageGet function, while it receives the base address of the CAN controller not the controller Id
5- bClrPendingInt is declared but not defined which is sent to CANMessageGet function.

**Comment by smsm2014** [comment]
Started working in this issue
