### ISSUE TITLE
CanDev_SetControllerModeFix

### ISSUE THREAD

**Issue by AAdelBayoumi** [autosarzs/Dev#46]
1.Check for the module init state not controller:
[SWS_Can_00198] if the module is not yet initialized, the function Can_SetControllerMode shall raise development error CAN_E_UNINIT and return E_NOT_OK.

2. when request is accepted the function should return E_OK

3. Code duplication for duplications

**Comment by ahmedwahdan** [comment]
those two points are not resolved in the commit.

1. when request is accepted the function should return E_OK
2. Code duplication for duplication
